version: "3.5"

services:
  gitlab:
    container_name: gitlab
    image: gitlab/gitlab-ce:latest
    restart: always
    ports:
      - "2222:22"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url ${GITLAB_EXTERNAL_URL}
        nginx['listen_https'] = false
        nginx['listen_port'] = 80
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = ${GITLAB_SMTP_ADDR}
        gitlab_rails['smtp_port'] = ${GITLAB_SMTP_PORT}
        gitlab_rails['smtp_user_name'] = ${GITLAB_SMTP_USER}
        gitlab_rails['smtp_password'] = ${GITLAB_SMTP_PASSWORD}
        gitlab_rails['smtp_domain'] = ${GITLAB_SMTP_DOMAIN}
        gitlab_rails['smtp_authentication'] = "login"
        gitlab_rails['smtp_enable_starttls_auto'] = true
        gitlab_rails['smtp_tls'] = false
        gitlab_rails['smtp_openssl_verify_mode'] = 'peer'
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
    labels:
      - traefik.http.routers.gitlab.rule=Host(${GITLAB_DOMAIN})
      - traefik.http.routers.gitlab.entrypoints=websecure
      - traefik.http.routers.gitlab.tls.certresolver=le
      - traefik.http.services.gitlab.loadbalancer.server.port=80
      - traefik.docker.network=traefik-proxy
      - traefik.tcp.routers.gitlab-ssh.rule=HostSNI(${GITLAB_DOMAIN})
      - traefik.tcp.routers.gitlab-ssh.entrypoints=ssh
      - traefik.tcp.routers.gitlab-ssh.service=gitlab-ssh-svc
      - traefik.tcp.services.gitlab-ssh-svc.loadbalancer.server.port=2222
    volumes:
      - ./volumes/config:/etc/gitlab
      - ./volumes/logs:/var/log/gitlab
      - ./volumes/data:/var/opt/gitlab
    networks:
      traefik-proxy:
      private:
      gitlab-network:
  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    container_name: gitlab-runner
    volumes:
      - ./volumes/runner/config/:/etc/gitlab-runner:Z
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      gitlab-network:
    labels:
      - traefik.enable=false
networks:
  traefik-proxy:
    name: traefik-proxy
    external: false
  private:
    name: private
    external: false
  gitlab-network:
    name: gitlab-network
    external: false
